# Generated by Django 2.2.6 on 2019-11-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191121_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Diary',
        ),
    ]
