# Generated by Django 2.2.6 on 2019-11-21 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191121_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'My_Dairy_Entries'},
        ),
        migrations.RemoveField(
            model_name='diary',
            name='name',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='paradigm',
        ),
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 21, 17, 40, 50, 277258)),
        ),
        migrations.AddField(
            model_name='diary',
            name='text',
            field=models.TextField(default='my dairy'),
        ),
    ]
