# Generated by Django 2.2.6 on 2019-11-21 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20191121_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 21, 22, 33, 28, 694177)),
        ),
    ]
